In [2]:
# SUBSET OF DATA FRAME
# 1. retrive columns
# 2. retrive rows using loc[] and iloc[] -- Properties
import pandas as pd

In [3]:
mydict ={'col1':[1,2,3,4], 'col2':[5,6,7,8], 'col3':['one','two','three','four']}
# in this dict the keys will become columns of the df
import pandas as pd

df = pd.DataFrame(mydict)
df

   col1  col2   col3
0     1     5    one
1     2     6    two
2     3     7  three
3     4     8   four

In [4]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='str')

In [5]:
df.index
# rangeindex class object

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df['col1']

In [19]:
df[['col1','col2']] # we have to add this columns in list for more than 1 column in df

   col1  col2
0     1     5
1     2     6
2     3     7
3     4     8

In [20]:
df['col2'] , df['col1'] # always go for above df frame

(0    5
 1    6
 2    7
 3    8
 Name: col2, dtype: int64,
 0    1
 1    2
 2    3
 3    4
 Name: col1, dtype: int64)

In [22]:
# based on condition if we have to get the columns
# col1 values should be greater than 1
df[df['col1'] >1]

   col1  col2   col3
1     2     6    two
2     3     7  three
3     4     8   four

In [27]:
df [(df['col1'] >1) & (df['col3'] != 'three')]

# where we are giving 2 conditions we will always put the conditions in () -- simple brackets

   col1  col2  col3
1     2     6   two
3     4     8  four

In [29]:
## based on the above condition i want column-3 value only always give the columns values in list format -- [['columns','columns']]

df [(df['col1'] >1) & (df['col3'] != 'three')][['col3','col1']]

   col3  col1
1   two     2
3  four     4

In [40]:
# display col-1 data where col2 <7

df[df['col2'] < 7]['col1']

0    1
1    2
Name: col1, dtype: int64

In [42]:
# retrive columns using loc and iloc

df.loc[1:3]

   col1  col2   col3
1     2     6    two
2     3     7  three
3     4     8   four

In [49]:
# retrive columns using iloc
# in iloc last row is excluded

df.iloc[1:3]

1      two
2    three
Name: col3, dtype: str

In [51]:
# only col3 data i want

df.loc[1:3,'col3']

1      two
2    three
3     four
Name: col3, dtype: str

In [52]:


df.iloc[1:3, 2]

1      two
2    three
Name: col3, dtype: str

In [54]:
# only col3 and col1 we want

df.loc[1:3,['col3', 'col1']]

    col3  col1
1    two     2
2  three     3
3   four     4

In [56]:
# only col3 and col1 we want with iloc we have to display

df.iloc[1:3,[2,0]]

    col3  col1
1    two     2
2  three     3

In [57]:
# only col2 with all rows, we want with iloc we have to display

df.iloc[:,[1]]

   col2
0     5
1     6
2     7
3     8

In [62]:
# all rows using 1 column using loc we have to display
# general foramt -- [r1:r2:step, c1:c2:step]
df.loc[:, 'col1']

0    1
1    2
2    3
3    4
Name: col1, dtype: int64

In [69]:
# general foramt -- [r1:r2:step, c1:c2:step]
df[0::2]

   col1  col2   col3
0     1     5    one
2     3     7  three

In [70]:
df.iloc[0::2, 0::2]

   col1   col3
0     1    one
2     3  three

In [73]:
# retrieve rows based on a query
# df.query('condition')
# mention condition always in string format
df.query('col1 > 2')

   col1  col2   col3
2     3     7  three
3     4     8   four

In [74]:
df.query('2*col1 >= col2')  # based on the condition

   col1  col2  col3
3     4     8  four

In [78]:
# where col 3 values will be 3 & 4

df.query(" col3 in ['three','four']")

   col1  col2   col3
2     3     7  three
3     4     8   four

In [79]:
# where col 3 values not in  3 & 4

df.query(" col3 not in ['three','four']")

   col1  col2 col3
0     1     5  one
1     2     6  two

In [83]:

df.query(" col2 != [5,7]")

   col1  col2  col3
1     2     6   two
3     4     8  four

In [ ]:
# working with columns ----------------------------

In [1]:
import pandas as pd

In [2]:
tpl = ((1001, 'nagesh'), (1002,'laxmi'), (1003, 'ganesh'), (1004, 'vinay'))

In [6]:
df = pd.DataFrame(tpl) # this will not display columns names
df

      0       1
0  1001  nagesh
1  1002   laxmi
2  1003  ganesh
3  1004   vinay

In [7]:
# we have to mention columns names
# column names
df.columns = ['id','names']
df

     id   names
0  1001  nagesh
1  1002   laxmi
2  1003  ganesh
3  1004   vinay

In [11]:
# TO RENAME THE COLUMNS NAMES
# using rename method()
# always give the column names in dictonary
df1 = df.rename(columns ={'id':'EmpId', 'names':'Names'})
df1

   EmpId   Names
0   1001  nagesh
1   1002   laxmi
2   1003  ganesh
3   1004   vinay

In [12]:
# TO RENAME THE COLUMNS NAMES
# using rename method()
# always give the column names in dictonary
# if we don't want to modify the data frame in same data frame we want to modify the data then use
# inplace =True

df.rename(columns ={'id':'EmpId', 'names':'Names'}, inplace =True)
df

   EmpId   Names
0   1001  nagesh
1   1002   laxmi
2   1003  ganesh
3   1004   vinay

In [13]:
# adding the new column to a dataframe

df['Department'] = 'Sales'
df

   EmpId   Names Department
0   1001  nagesh      Sales
1   1002   laxmi      Sales
2   1003  ganesh      Sales
3   1004   vinay      Sales

In [14]:
# adding the new column to a dataframe and inserting the values to that specific column

df['Department'] = ['Sales','HR','Production','Sales']
df

   EmpId   Names  Department
0   1001  nagesh       Sales
1   1002   laxmi          HR
2   1003  ganesh  Production
3   1004   vinay       Sales

In [22]:
# insert the column in between the dataframe

# df.insert(loc=1, column='Salary', value =[35000, 42000, 55000, 24000])
df

   EmpId  Salary   Names  Department
0   1001   35000  nagesh       Sales
1   1002   42000   laxmi          HR
2   1003   55000  ganesh  Production
3   1004   24000   vinay       Sales

In [24]:
# creating the new column from a existing column
#  derived column
# this column will ber created at THE LAST OF A DATAFRAME
df['Tax'] = df['Salary']*0.1
df

   EmpId  Salary   Names  Department     Tax
0   1001   35000  nagesh       Sales  3500.0
1   1002   42000   laxmi          HR  4200.0
2   1003   55000  ganesh  Production  5500.0
3   1004   24000   vinay       Sales  2400.0

In [27]:
# CREATING THE NEW COLUMN USING A LAMBDA FUNCTION
# LAMBDA FUNCTION
# NOAT :- with lambda always use assign() method

df2 = df.assign(PF = lambda x: x.Salary * 12.5/100) # x is a total dataframe object
df2

   EmpId  Salary   Names  Department     Tax      PF
0   1001   35000  nagesh       Sales  3500.0  4375.0
1   1002   42000   laxmi          HR  4200.0  5250.0
2   1003   55000  ganesh  Production  5500.0  6875.0
3   1004   24000   vinay       Sales  2400.0  3000.0

In [28]:
# gross salary = salary - PF -Tax
# net salary = Salary + DA+ HRA -PF -IncomTax
# x -- represent dataframe object
# df3 = df2.assign( Gross_Salary = lambda x : x[Salary] - x[PF] - x[Tax]) # like this also we can mention
df3

   EmpId  Salary   Names  Department     Tax      PF  Gross_Salary
0   1001   35000  nagesh       Sales  3500.0  4375.0       27125.0
1   1002   42000   laxmi          HR  4200.0  5250.0       32550.0
2   1003   55000  ganesh  Production  5500.0  6875.0       42625.0
3   1004   24000   vinay       Sales  2400.0  3000.0       18600.0