In [34]:
import pandas as pd

In [35]:
df1 = pd.DataFrame({'Player_name':['Virat Kolhi', 'Rohit Sharma', 'Rahul Dravid'], 'Age':[20,30,40]})
df1

    Player_name  age
0   Virat Kolhi   20
1  Rohit Sharma   30
2  Rahul Dravid   40

In [37]:
df2 = pd.DataFrame({'Player_name':['Virat Kolhi', 'Rohit Sharma', 'ishan sharma','Hardik Pandya'], 'Salary':[23,45,56,50]})
df2

     Player_name  Salary
0    Virat Kolhi      23
1   Rohit Sharma      45
2   ishan sharma      56
3  Hardik Pandya      50

In [44]:
# inner join

pd.merge(df1,df2, on='Player_name',how='inner')

    Player_name  age  Salary
0   Virat Kolhi   20      23
1  Rohit Sharma   30      45

In [45]:
# left join
pd.merge(df1,df2, on='Player_name',how='left')

    Player_name  age  Salary
0   Virat Kolhi   20    23.0
1  Rohit Sharma   30    45.0
2  Rahul Dravid   40     NaN

In [46]:
# right join
pd.merge(df1,df2, on='Player_name',how='right')

     Player_name   age  Salary
0    Virat Kolhi  20.0      23
1   Rohit Sharma  30.0      45
2   ishan sharma   NaN      56
3  Hardik Pandya   NaN      50

In [48]:
# outer join
pd.merge(df1,df2, on='Player_name',how='outer')

     Player_name   age  Salary
0  Hardik Pandya   NaN    50.0
1   Rahul Dravid  40.0     NaN
2   Rohit Sharma  30.0    45.0
3    Virat Kolhi  20.0    23.0
4   ishan sharma   NaN    56.0

In [51]:
# how to join when column names does not match ??

df3 = pd.DataFrame({'Sports_person':['Virat Kolhi', 'Rohit Sharma', 'ishan sharma','Hardik Pandya'], 'Salary':[23,45,56,50]})
df3

    Player_name  age Sports_person  Salary
0   Virat Kolhi   20   Virat Kolhi      23
1  Rohit Sharma   30  Rohit Sharma      45

In [52]:
# merge
pd.merge(df1,df3, left_on = 'Player_name', right_on='Sports_person', how='inner')

    Player_name  age Sports_person  Salary
0   Virat Kolhi   20   Virat Kolhi      23
1  Rohit Sharma   30  Rohit Sharma      45

In [53]:
# merge left
pd.merge(df1,df3, left_on = 'Player_name', right_on='Sports_person', how='left')

    Player_name  age Sports_person  Salary
0   Virat Kolhi   20   Virat Kolhi    23.0
1  Rohit Sharma   30  Rohit Sharma    45.0
2  Rahul Dravid   40           NaN     NaN

In [62]:
# CONCAT -----------------------------------------------
# to join the tables side by side

In [63]:
# concat always pas the data frames in list format

pd.concat([df1,df3])

    Player_name   age  Sports_person  Salary
0   Virat Kolhi  20.0            NaN     NaN
1  Rohit Sharma  30.0            NaN     NaN
2  Rahul Dravid  40.0            NaN     NaN
0           NaN   NaN    Virat Kolhi    23.0
1           NaN   NaN   Rohit Sharma    45.0
2           NaN   NaN   ishan sharma    56.0
3           NaN   NaN  Hardik Pandya    50.0

In [64]:
# concat always pas the data frames in list format

pd.concat([df1,df2,df3])

     Player_name   age  Salary  Sports_person
0    Virat Kolhi  20.0     NaN            NaN
1   Rohit Sharma  30.0     NaN            NaN
2   Rahul Dravid  40.0     NaN            NaN
0    Virat Kolhi   NaN    23.0            NaN
1   Rohit Sharma   NaN    45.0            NaN
2   ishan sharma   NaN    56.0            NaN
3  Hardik Pandya   NaN    50.0            NaN
0            NaN   NaN    23.0    Virat Kolhi
1            NaN   NaN    45.0   Rohit Sharma
2            NaN   NaN    56.0   ishan sharma
3            NaN   NaN    50.0  Hardik Pandya

In [65]:
# on the above dataframe we want to change the index

pd.concat([df1,df2,df3], ignore_index='True')

      Player_name   age  Salary  Sports_person
0     Virat Kolhi  20.0     NaN            NaN
1    Rohit Sharma  30.0     NaN            NaN
2    Rahul Dravid  40.0     NaN            NaN
3     Virat Kolhi   NaN    23.0            NaN
4    Rohit Sharma   NaN    45.0            NaN
5    ishan sharma   NaN    56.0            NaN
6   Hardik Pandya   NaN    50.0            NaN
7             NaN   NaN    23.0    Virat Kolhi
8             NaN   NaN    45.0   Rohit Sharma
9             NaN   NaN    56.0   ishan sharma
10            NaN   NaN    50.0  Hardik Pandya

In [66]:
# Concat column wise

pd.concat([df1,df2], axis =1)

    Player_name   age    Player_name  Salary
0   Virat Kolhi  20.0    Virat Kolhi      23
1  Rohit Sharma  30.0   Rohit Sharma      45
2  Rahul Dravid  40.0   ishan sharma      56
3           NaN   NaN  Hardik Pandya      50

In [ ]:
# SQL-------------------
# titanic dataset
# SELECT
# WHERE
# GROUP BY
#

In [67]:
df = pd.read_csv('D:/AVD/PYTHON/datasets-20260827T080306Z-1-001/datasets/adv-datasets/adv-datasets/titanic.csv')

In [68]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [69]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [71]:
df['Pclass'] # also can write df.Plass

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [74]:
df[['Pclass', 'Name']]

     Pclass                                               Name
0         3                            Braund, Mr. Owen Harris
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         3                             Heikkinen, Miss. Laina
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         3                           Allen, Mr. William Henry
..      ...                                                ...
886       2                              Montvila, Rev. Juozas
887       1                       Graham, Miss. Margaret Edith
888       3           Johnston, Miss. Catherine Helen "Carrie"
889       1                              Behr, Mr. Karl Howell
890       3                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [75]:
df[5:10]  # to select the rows last n-1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [76]:
df[1:20:2]  # alternate rows i need to check step size we need to provide

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C

In [79]:
df[1:20:2][['PassengerId','Name']]

    PassengerId                                               Name
1             2  Cumings, Mrs. John Bradley (Florence Briggs Th...
3             4       Futrelle, Mrs. Jacques Heath (Lily May Peel)
5             6                                   Moran, Mr. James
7             8                     Palsson, Master. Gosta Leonard
9            10                Nasser, Mrs. Nicholas (Adele Achem)
11           12                           Bonnell, Miss. Elizabeth
13           14                        Andersson, Mr. Anders Johan
15           16                    Hewlett, Mrs. (Mary D Kingcome)
17           18                       Williams, Mr. Charles Eugene
19           20                            Masselmani, Mrs. Fatima

In [ ]:
# passenger who have survi

In [83]:
df[df['Survived'] ==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,1,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,1,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,1,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,1,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [93]:
len(df.Survived == 1)

891

In [87]:
df.loc[10]

PassengerId                                 11
Survived                                     1
Pclass                                       3
Name           Sandstrom, Miss. Marguerite Rut
Sex                                     female
Age                                        4.0
SibSp                                        1
Parch                                        1
Ticket                                 PP 9549
Fare                                      16.7
Cabin                                       G6
Embarked                                     S
Name: 10, dtype: object

In [89]:
df.loc[[10,15,20],['Name', 'Age']] # using loc

                               Name   Age
10  Sandstrom, Miss. Marguerite Rut   4.0
15  Hewlett, Mrs. (Mary D Kingcome)  55.0
20             Fynney, Mr. Joseph J  35.0

In [92]:
df.iloc[[10,15,20],[3,5]] # using iloc

                               Name   Age
10  Sandstrom, Miss. Marguerite Rut   4.0
15  Hewlett, Mrs. (Mary D Kingcome)  55.0
20             Fynney, Mr. Joseph J  35.0

In [94]:
# in the 2nd row 3rd column element

df.iloc[2,3]  # second row, third column

'Heikkinen, Miss. Laina'

In [97]:
# iloc -- it will exclude last record
df.iloc[5:10, 3]

5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: str

In [98]:
# loc -- it will include last record

df.loc[5:10, 'Name']

5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
Name: Name, dtype: str

In [103]:
# display the rows who's age is above 45

df[(df['Age']>45) & (df['Sex']=='male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,1,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
33,34,1,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,1,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
92,93,1,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,E31,S
94,95,1,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
771,772,1,3,"Jensen, Mr. Niels Peder",male,48.0,0,0,350047,7.8542,NaN,S
789,790,1,1,"Guggenheim, Mr. Benjamin",male,46.0,0,0,PC 17593,79.2000,B82 B84,C
851,852,1,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
873,874,1,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S

In [106]:
df[(df['Age']>45) & (df['Sex']=='male')][['Name','Fare']]

                               Name     Fare
6           McCarthy, Mr. Timothy J  51.8625
33            Wheadon, Mr. Edward H  10.5000
54   Ostby, Mr. Engelhart Cornelius  61.9792
92      Chaffee, Mr. Herbert Fuller  61.1750
94                Coxon, Mr. Daniel   7.2500
..                              ...      ...
771         Jensen, Mr. Niels Peder   7.8542
789        Guggenheim, Mr. Benjamin  79.2000
851             Svensson, Mr. Johan   7.7750
857           Daly, Mr. Peter Denis  26.5500
873     Vander Cruyssen, Mr. Victor   9.0000

[73 rows x 2 columns]

In [107]:
# WHERE

import pandas as pd
import numpy as np

In [113]:
df =pd.DataFrame(data=np.random.randint(0,100,(4,3)),
                 columns =('Test1', 'Test2', 'Test3'),
                 index = ['Vinay','Anil','Gopal','Rao'])
df

       Test1  Test2  Test3
Vinay     42     60      6
Anil      50     21     25
Gopal     59     57     21
Rao       45     45     71

In [110]:
df<80 # this will give true or false

       Test1  Test2  Test3
Vinay   True   True   True
Anil    True   True   True
Gopal   True   True   True
Rao    False   True   True

In [111]:
df.where(df<80, 'A+') ## here where this is condition df<80 is false it will replace it with A+

      Test1  Test2  Test3
Vinay    51     49     74
Anil      4     75     27
Gopal     7     63     29
Rao      A+     78     59

In [112]:
df.where(df>50, 'Poor') # condition should be false then only it will

      Test1 Test2 Test3
Vinay    51  Poor    74
Anil   Poor    75  Poor
Gopal  Poor    63  Poor
Rao      99    78    59

In [114]:
df2 =pd.DataFrame(data=np.random.randint(0,100,(4,3)),
                 columns =('Test1', 'Test2', 'Test3'),
                 index = ['Vinay','Anil','Gopal','Rao'])
df2

       Test1  Test2  Test3
Vinay     25     67      5
Anil      63     29      5
Gopal     38     42     71
Rao       16     32     47

In [117]:
df

       Test1  Test2  Test3
Vinay     42     60      6
Anil      50     21     25
Gopal     59     57     21
Rao       45     45     71

In [119]:
df.where(df<30, df2)

       Test1  Test2  Test3
Vinay     25     67      6
Anil      63     21     25
Gopal     38     42     21
Rao       16     32     47

In [120]:
 df = pd.read_csv("D:/AVD/PYTHON/datasets-20260827T080306Z-1-001/datasets/adv-datasets/adv-datasets/cities_weather.csv")
 df

           day      city  temperature  windspeed   event
0   01-01-2017  new york           32          6    Rain
1   01-02-2017  new york           36          7   Sunny
2   01-03-2017  new york           28         12    Snow
3   01-04-2017  new york           33          7   Sunny
4   01-01-2017    mumbai           90          5   Sunny
5   01-02-2017    mumbai           85         12     Fog
6   01-03-2017    mumbai           87         15     Fog
7   01-04-2017    mumbai           92          5    Rain
8   01-01-2017     paris           45         20   Sunny
9   01-02-2017     paris           50         13  Cloudy
10  01-03-2017     paris           54          8  Cloudy
11  01-04-2017     paris           42         10  Cloudy

In [124]:
df1 = df.groupby('city') # when you use group by method it will return DataFrameGroupBy cclass object
df1

In [125]:
# after performing the group by method i will group all the rows from city columns ans stores in seprate dataframe city_df

for city, city_df in df1:
    print(city)
    print(city_df)

mumbai
          day    city  temperature  windspeed  event
4  01-01-2017  mumbai           90          5  Sunny
5  01-02-2017  mumbai           85         12    Fog
6  01-03-2017  mumbai           87         15    Fog
7  01-04-2017  mumbai           92          5   Rain
new york
          day      city  temperature  windspeed  event
0  01-01-2017  new york           32          6   Rain
1  01-02-2017  new york           36          7  Sunny
2  01-03-2017  new york           28         12   Snow
3  01-04-2017  new york           33          7  Sunny
paris
           day   city  temperature  windspeed   event
8   01-01-2017  paris           45         20   Sunny
9   01-02-2017  paris           50         13  Cloudy
10  01-03-2017  paris           54          8  Cloudy
11  01-04-2017  paris           42         10  Cloudy

In [129]:
# we have taken out data frame using get_group() method

Mumbai_df2 = df1.get_group('mumbai')
Mumbai_df2

          day    city  temperature  windspeed  event
4  01-01-2017  mumbai           90          5  Sunny
5  01-02-2017  mumbai           85         12    Fog
6  01-03-2017  mumbai           87         15    Fog
7  01-04-2017  mumbai           92          5   Rain

In [130]:
Mumbai_df2.max()  # on alphabetical order i will show on both string and numeric type of data

day            01-04-2017
city               mumbai
temperature            92
windspeed              15
event               Sunny
dtype: object

In [131]:
Mumbai_df2.min()

day            01-01-2017
city               mumbai
temperature            85
windspeed               5
event                 Fog
dtype: object

In [132]:
# if we want to perform this on numeric type of data
Mumbai_df2['temperature'].max()

np.int64(92)

In [133]:
# if we want to perform this on numeric type of data
Mumbai_df2['temperature'].sum()

np.int64(354)

In [135]:
# if we want to perform this on numeric type of data
Mumbai_df2['windspeed'].sum()
print(Mumbai_df2['windspeed'].sum())

37

In [137]:
# to find max temperature in paris

paris_df2 = df1.get_group('paris')
paris_df2

           day   city  temperature  windspeed   event
8   01-01-2017  paris           45         20   Sunny
9   01-02-2017  paris           50         13  Cloudy
10  01-03-2017  paris           54          8  Cloudy
11  01-04-2017  paris           42         10  Cloudy

In [138]:
# to find max temperature in paris
paris_df2['temperature'].max()

np.int64(54)

In [139]:
# to find number of values in paris
paris_df2['temperature'].count()

np.int64(4)

In [141]:
# to find average temperature in paris
print(paris_df2['temperature'].mean())

47.75

In [142]:
df['temperature'].mean() # this is showing all the 3 city temperature aggregate we are using df please ccheck above

np.float64(56.166666666666664)