In [60]:
import pandas as pd
import numpy as np
import matplotlib as sns

In [61]:
df = pd.read_csv("D:/AVD/PYTHON/Practice_file.txt")
df

,order_id,order_date,customer_id,customer_name,gender,age,city,state,product_category,product,quantity,unit_price,discount,payment_method,order_status,rating
0,1001,2026-01-05,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Laptop,1,65000,0.10,Credit Card,Delivered,5.0
1,1002,2026-01-07,C002,Priya,Female,32,Mumbai,Maharashtra,Clothing,T-Shirt,3,800,0.05,UPI,Delivered,4.0
2,1003,2026-01-10,C003,Amit,Male,24,Nagpur,Maharashtra,Electronics,Headphones,2,2500,0.00,UPI,Delivered,5.0
3,1004,2026-01-12,C004,Neha,Female,29,Bangalore,Karnataka,Furniture,Chair,2,4500,0.15,Debit Card,Delivered,4.0
4,1005,2026-01-15,C005,Rohit,Male,35,Delhi,Delhi,Electronics,Mobile Phone,1,28000,0.08,Credit Card,Delivered,5.0
5,1006,2026-01-18,C006,Sneha,Female,27,Hyderabad,Telangana,Clothing,Jeans,2,2200,0.10,UPI,Delivered,4.0
6,1007,2026-01-20,C007,Vikas,Male,41,Pune,Maharashtra,Grocery,Rice,5,900,0.03,UPI,Delivered,4.0
7,1008,2026-01-23,C008,Anjali,Female,23,Mumbai,Maharashtra,Beauty,Face Cream,4,650,0.05,Credit Card,Delivered,5.0
8,1009,2026-01-25,C009,Karan,Male,31,Chennai,Tamil Nadu,Electronics,Smart Watch,1,7500,0.12,Debit Card,Delivered,4.0
9,1010,2026-01-28,C010,Pooja,Female,38,Delhi,Delhi,Furniture,Sofa,1,32000,0.20,Credit Card,Cancelled,NaN
10,1011,2026-02-02,C011,Akash,Male,26,Pune,Maharashtra,Electronics,Keyboard,2,1800,0.00,UPI,Delivered,4.0
11,1012,2026-02-05,C012,Riya,Female,30,Bangalore,Karnataka,Clothing,Dress,2,3500,0.10,UPI,Delivered,5.0
12,1013,2026-02-08,C013,Manish,Male,45,Mumbai,Maharashtra,Grocery,Cooking Oil,3,1500,0.05,Cash,Delivered,3.0
13,1014,2026-02-10,C014,Kavita,Female,34,Hyderabad,Telangana,Beauty,Perfume,2,2800,0.15,Credit Card,Delivered,4.0
14,1015,2026-02-13,C015,Suresh,Male,52,Nagpur,Maharashtra,Furniture,Table,1,8500,0.10,Debit Card,Delivered,5.0
15,1016,2026-02-16,C016,Meera,Female,25,Chennai,Tamil Nadu,Electronics,Tablet,1,22000,0.05,UPI,Delivered,4.0
16,1017,2026-02-18,C017,Arjun,Male,29,Pune,Maharashtra,Clothing,Shoes,2,4500,0.12,Credit Card,Delivered,5.0
17,1018,2026-02-21,C018,Simran,Female,36,Delhi,Delhi,Grocery,Wheat,4,700,0.00,UPI,Delivered,4.0
18,1019,2026-02-24,C019,Deepak,Male,40,Mumbai,Maharashtra,Electronics,Monitor,1,14500,0.10,Credit Card,Returned,2.0
19,1020,2026-02-27,C020,Shweta,Female,28,Bangalore,Karnataka,Beauty,Shampoo,5,450,0.05,UPI,Delivered,4.0
20,1021,2026-03-01,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Mouse,2,1200,0.00,UPI,Delivered,5.0
21,1022,2026-03-04,C002,Priya,Female,32,Mumbai,Maharashtra,Clothing,Jacket,1,5500,0.15,Credit Card,Delivered,4.0
22,1023,2026-03-07,C003,Amit,Male,24,Nagpur,Maharashtra,Grocery,Sugar,5,500,0.05,Cash,Delivered,3.0
23,1024,2026-03-10,C004,Neha,Female,29,Bangalore,Karnataka,Furniture,Bed,1,28000,0.20,Credit Card,Delivered,5.0
24,1025,2026-03-13,C005,Rohit,Male,35,Delhi,Delhi,Electronics,Power Bank,3,1800,0.10,UPI,Delivered,4.0
25,1026,2026-03-16,C006,Sneha,Female,27,Hyderabad,Telangana,Beauty,Lipstick,3,900,0.08,UPI,Delivered,5.0
26,1027,2026-03-19,C007,Vikas,Male,41,Pune,Maharashtra,Grocery,Milk,10,70,0.02,Cash,Delivered,4.0
27,1028,2026-03-22,C008,Anjali,Female,23,Mumbai,Maharashtra,Clothing,Skirt,2,1800,0.10,Credit Card,Delivered,4.0
28,1029,2026-03-25,C009,Karan,Male,31,Chennai,Tamil Nadu,Electronics,Earbuds,2,3200,0.05,UPI,Delivered,5.0
29,1030,2026-03-28,C010,Pooja,Female,38,Delhi,Delhi,Furniture,Dining Table,1,24000,0.15,Debit Card,Cancelled,NaN

In [62]:
# total count of row = 30
len(df)

30

In [63]:
# this will also tell you how many rows are there in python

df.index

RangeIndex(start=0, stop=30, step=1)

In [64]:
df[0:5] # this will shows us rows

,order_id,order_date,customer_id,customer_name,gender,age,city,state,product_category,product,quantity,unit_price,discount,payment_method,order_status,rating
0,1001,2026-01-05,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Laptop,1,65000,0.10,Credit Card,Delivered,5.0
1,1002,2026-01-07,C002,Priya,Female,32,Mumbai,Maharashtra,Clothing,T-Shirt,3,800,0.05,UPI,Delivered,4.0
2,1003,2026-01-10,C003,Amit,Male,24,Nagpur,Maharashtra,Electronics,Headphones,2,2500,0.00,UPI,Delivered,5.0
3,1004,2026-01-12,C004,Neha,Female,29,Bangalore,Karnataka,Furniture,Chair,2,4500,0.15,Debit Card,Delivered,4.0
4,1005,2026-01-15,C005,Rohit,Male,35,Delhi,Delhi,Electronics,Mobile Phone,1,28000,0.08,Credit Card,Delivered,5.0

In [65]:
df.iloc[:,[1,7]] # this will give us specific columns as mentioned -- 1,7 and : -- all rows

    order_date        state
0   2026-01-05  Maharashtra
1   2026-01-07  Maharashtra
2   2026-01-10  Maharashtra
3   2026-01-12    Karnataka
4   2026-01-15        Delhi
5   2026-01-18    Telangana
6   2026-01-20  Maharashtra
7   2026-01-23  Maharashtra
8   2026-01-25   Tamil Nadu
9   2026-01-28        Delhi
10  2026-02-02  Maharashtra
11  2026-02-05    Karnataka
12  2026-02-08  Maharashtra
13  2026-02-10    Telangana
14  2026-02-13  Maharashtra
15  2026-02-16   Tamil Nadu
16  2026-02-18  Maharashtra
17  2026-02-21        Delhi
18  2026-02-24  Maharashtra
19  2026-02-27    Karnataka
20  2026-03-01  Maharashtra
21  2026-03-04  Maharashtra
22  2026-03-07  Maharashtra
23  2026-03-10    Karnataka
24  2026-03-13        Delhi
25  2026-03-16    Telangana
26  2026-03-19  Maharashtra
27  2026-03-22  Maharashtra
28  2026-03-25   Tamil Nadu
29  2026-03-28        Delhi

In [66]:
df[0::2] # general format is [r1:r2:step, c1:c2:step]

,order_id,order_date,customer_id,customer_name,gender,age,city,state,product_category,product,quantity,unit_price,discount,payment_method,order_status,rating
0,1001,2026-01-05,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Laptop,1,65000,0.10,Credit Card,Delivered,5.0
2,1003,2026-01-10,C003,Amit,Male,24,Nagpur,Maharashtra,Electronics,Headphones,2,2500,0.00,UPI,Delivered,5.0
4,1005,2026-01-15,C005,Rohit,Male,35,Delhi,Delhi,Electronics,Mobile Phone,1,28000,0.08,Credit Card,Delivered,5.0
6,1007,2026-01-20,C007,Vikas,Male,41,Pune,Maharashtra,Grocery,Rice,5,900,0.03,UPI,Delivered,4.0
8,1009,2026-01-25,C009,Karan,Male,31,Chennai,Tamil Nadu,Electronics,Smart Watch,1,7500,0.12,Debit Card,Delivered,4.0
10,1011,2026-02-02,C011,Akash,Male,26,Pune,Maharashtra,Electronics,Keyboard,2,1800,0.00,UPI,Delivered,4.0
12,1013,2026-02-08,C013,Manish,Male,45,Mumbai,Maharashtra,Grocery,Cooking Oil,3,1500,0.05,Cash,Delivered,3.0
14,1015,2026-02-13,C015,Suresh,Male,52,Nagpur,Maharashtra,Furniture,Table,1,8500,0.10,Debit Card,Delivered,5.0
16,1017,2026-02-18,C017,Arjun,Male,29,Pune,Maharashtra,Clothing,Shoes,2,4500,0.12,Credit Card,Delivered,5.0
18,1019,2026-02-24,C019,Deepak,Male,40,Mumbai,Maharashtra,Electronics,Monitor,1,14500,0.10,Credit Card,Returned,2.0
20,1021,2026-03-01,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Mouse,2,1200,0.00,UPI,Delivered,5.0
22,1023,2026-03-07,C003,Amit,Male,24,Nagpur,Maharashtra,Grocery,Sugar,5,500,0.05,Cash,Delivered,3.0
24,1025,2026-03-13,C005,Rohit,Male,35,Delhi,Delhi,Electronics,Power Bank,3,1800,0.10,UPI,Delivered,4.0
26,1027,2026-03-19,C007,Vikas,Male,41,Pune,Maharashtra,Grocery,Milk,10,70,0.02,Cash,Delivered,4.0
28,1029,2026-03-25,C009,Karan,Male,31,Chennai,Tamil Nadu,Electronics,Earbuds,2,3200,0.05,UPI,Delivered,5.0

In [67]:
df.iloc[0::2, 0::2] # this will print all the corresponding rows and columns as per the mentioned details

,order_id,customer_id,gender,city,product_category,quantity,discount,order_status
0,1001,C001,Male,Pune,Electronics,1,0.10,Delivered
2,1003,C003,Male,Nagpur,Electronics,2,0.00,Delivered
4,1005,C005,Male,Delhi,Electronics,1,0.08,Delivered
6,1007,C007,Male,Pune,Grocery,5,0.03,Delivered
8,1009,C009,Male,Chennai,Electronics,1,0.12,Delivered
10,1011,C011,Male,Pune,Electronics,2,0.00,Delivered
12,1013,C013,Male,Mumbai,Grocery,3,0.05,Delivered
14,1015,C015,Male,Nagpur,Furniture,1,0.10,Delivered
16,1017,C017,Male,Pune,Clothing,2,0.12,Delivered
18,1019,C019,Male,Mumbai,Electronics,1,0.10,Returned
20,1021,C001,Male,Pune,Electronics,2,0.00,Delivered
22,1023,C003,Male,Nagpur,Grocery,5,0.05,Delivered
24,1025,C005,Male,Delhi,Electronics,3,0.10,Delivered
26,1027,C007,Male,Pune,Grocery,10,0.02,Delivered
28,1029,C009,Male,Chennai,Electronics,2,0.05,Delivered

In [68]:
# retrive rows based on the query
#df.query()
df.query("gender == 'Male' & product_category == 'Electronics'")

,order_id,order_date,customer_id,customer_name,gender,age,city,state,product_category,product,quantity,unit_price,discount,payment_method,order_status,rating
0,1001,2026-01-05,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Laptop,1,65000,0.10,Credit Card,Delivered,5.0
2,1003,2026-01-10,C003,Amit,Male,24,Nagpur,Maharashtra,Electronics,Headphones,2,2500,0.00,UPI,Delivered,5.0
4,1005,2026-01-15,C005,Rohit,Male,35,Delhi,Delhi,Electronics,Mobile Phone,1,28000,0.08,Credit Card,Delivered,5.0
8,1009,2026-01-25,C009,Karan,Male,31,Chennai,Tamil Nadu,Electronics,Smart Watch,1,7500,0.12,Debit Card,Delivered,4.0
10,1011,2026-02-02,C011,Akash,Male,26,Pune,Maharashtra,Electronics,Keyboard,2,1800,0.00,UPI,Delivered,4.0
18,1019,2026-02-24,C019,Deepak,Male,40,Mumbai,Maharashtra,Electronics,Monitor,1,14500,0.10,Credit Card,Returned,2.0
20,1021,2026-03-01,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Mouse,2,1200,0.00,UPI,Delivered,5.0
24,1025,2026-03-13,C005,Rohit,Male,35,Delhi,Delhi,Electronics,Power Bank,3,1800,0.10,UPI,Delivered,4.0
28,1029,2026-03-25,C009,Karan,Male,31,Chennai,Tamil Nadu,Electronics,Earbuds,2,3200,0.05,UPI,Delivered,5.0

In [69]:
# loc[] -- locate, mention column name
#iloc[] -- locate using index, dont need to mention column names

df.loc[1:5,['customer_id','customer_name','product_category','city','state']]

  customer_id customer_name product_category       city        state
1        C002         Priya         Clothing     Mumbai  Maharashtra
2        C003          Amit      Electronics     Nagpur  Maharashtra
3        C004          Neha        Furniture  Bangalore    Karnataka
4        C005         Rohit      Electronics      Delhi        Delhi
5        C006         Sneha         Clothing  Hyderabad    Telangana

In [70]:
df.loc[1:5][['customer_id','customer_name','product_category','city','state']]

  customer_id customer_name product_category       city        state
1        C002         Priya         Clothing     Mumbai  Maharashtra
2        C003          Amit      Electronics     Nagpur  Maharashtra
3        C004          Neha        Furniture  Bangalore    Karnataka
4        C005         Rohit      Electronics      Delhi        Delhi
5        C006         Sneha         Clothing  Hyderabad    Telangana

In [71]:
# iloc
df.iloc[1:5,[1,2,3,4]]

   order_date customer_id customer_name  gender
1  2026-01-07        C002         Priya  Female
2  2026-01-10        C003          Amit    Male
3  2026-01-12        C004          Neha  Female
4  2026-01-15        C005         Rohit    Male

In [72]:
df.iloc[1:5,[1,4,5,6]]

   order_date  gender  age       city
1  2026-01-07  Female   32     Mumbai
2  2026-01-10    Male   24     Nagpur
3  2026-01-12  Female   29  Bangalore
4  2026-01-15    Male   35      Delhi

In [73]:
# ----------------------------------- working with columns ----------------------

In [74]:
import pandas as pd

In [75]:
# A TUPLE -------------------
tpl =((1010, "gaurav"),(1002,"laxman"),(1003,"ganesh"),(1004,"ram"))

In [76]:
df_tpl = pd.DataFrame(tpl) # CREATING A DATAFRAME OUT OF A TUPLE
df_tpl

      0       1
0  1010  gaurav
1  1002  laxman
2  1003  ganesh
3  1004     ram

In [77]:
df_tpl.columns = ['ID', 'NAME'] # NAMING COLUMNS FOR A DATAFRAME
df_tpl

     ID    NAME
0  1010  gaurav
1  1002  laxman
2  1003  ganesh
3  1004     ram

In [78]:
# TO RENAME THE COLUMNS NAMES
# using rename method()
df.head()

,order_id,order_date,customer_id,customer_name,gender,age,city,state,product_category,product,quantity,unit_price,discount,payment_method,order_status,rating
0,1001,2026-01-05,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Laptop,1,65000,0.10,Credit Card,Delivered,5.0
1,1002,2026-01-07,C002,Priya,Female,32,Mumbai,Maharashtra,Clothing,T-Shirt,3,800,0.05,UPI,Delivered,4.0
2,1003,2026-01-10,C003,Amit,Male,24,Nagpur,Maharashtra,Electronics,Headphones,2,2500,0.00,UPI,Delivered,5.0
3,1004,2026-01-12,C004,Neha,Female,29,Bangalore,Karnataka,Furniture,Chair,2,4500,0.15,Debit Card,Delivered,4.0
4,1005,2026-01-15,C005,Rohit,Male,35,Delhi,Delhi,Electronics,Mobile Phone,1,28000,0.08,Credit Card,Delivered,5.0

In [79]:
#df.rename(columns{'old_column_name':'new_column_name'}, inplace =True)

df.rename(columns = {'order_id':'Order_Id', 'order_date':'Order_Date', 'customer_id':'Customer_Id',
                     'gender':'Gender', 'age':'Age', 'city': 'City', 'state':'State',
                     'product_category' : 'Product_Category', 'product':'Product', 'quantity':'Quantity', 'payment_method': 'Payment_Method',
                     'order_status':'Order_Status','rating':'Rating', 'customer_name': 'Customer_Name'} , inplace =True)
df.head()

,Order_Id,Order_Date,Customer_Id,Customer_Name,Gender,Age,City,State,Product_Category,Product,Quantity,unit_price,discount,Payment_Method,Order_Status,Rating
0,1001,2026-01-05,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Laptop,1,65000,0.10,Credit Card,Delivered,5.0
1,1002,2026-01-07,C002,Priya,Female,32,Mumbai,Maharashtra,Clothing,T-Shirt,3,800,0.05,UPI,Delivered,4.0
2,1003,2026-01-10,C003,Amit,Male,24,Nagpur,Maharashtra,Electronics,Headphones,2,2500,0.00,UPI,Delivered,5.0
3,1004,2026-01-12,C004,Neha,Female,29,Bangalore,Karnataka,Furniture,Chair,2,4500,0.15,Debit Card,Delivered,4.0
4,1005,2026-01-15,C005,Rohit,Male,35,Delhi,Delhi,Electronics,Mobile Phone,1,28000,0.08,Credit Card,Delivered,5.0

In [80]:
# adding the new column
df1 = df.iloc[0: ,[0,1,8,9,10,11,12,13,14,15]]
df1.head()

,Order_Id,Order_Date,Product_Category,Product,Quantity,unit_price,discount,Payment_Method,Order_Status,Rating
0,1001,2026-01-05,Electronics,Laptop,1,65000,0.10,Credit Card,Delivered,5.0
1,1002,2026-01-07,Clothing,T-Shirt,3,800,0.05,UPI,Delivered,4.0
2,1003,2026-01-10,Electronics,Headphones,2,2500,0.00,UPI,Delivered,5.0
3,1004,2026-01-12,Furniture,Chair,2,4500,0.15,Debit Card,Delivered,4.0
4,1005,2026-01-15,Electronics,Mobile Phone,1,28000,0.08,Credit Card,Delivered,5.0

In [81]:
df2 = df.iloc[0: ,[2,3,4,5,6,7]]
df2.head()

  Customer_Id Customer_Name  Gender  Age       City        State
0        C001         Rahul    Male   28       Pune  Maharashtra
1        C002         Priya  Female   32     Mumbai  Maharashtra
2        C003          Amit    Male   24     Nagpur  Maharashtra
3        C004          Neha  Female   29  Bangalore    Karnataka
4        C005         Rohit    Male   35      Delhi        Delhi

In [82]:
df['State'].unique()

<StringArray>
['Maharashtra', 'Karnataka', 'Delhi', 'Telangana', 'Tamil Nadu']
Length: 5, dtype: str

In [83]:
# --- ADDING A NEW COLUMN TO A DATAFRAME ------------------------------

In [84]:
# new column
df2['Pincode'] = 440034

In [85]:
# -----------------------inserting the column in between columns -----------------------------------

In [86]:
# creating the derived column

In [87]:
df['Total'] = df['unit_price'] * df['discount']

In [88]:
df.head()

,Order_Id,Order_Date,Customer_Id,Customer_Name,Gender,Age,City,State,Product_Category,Product,Quantity,unit_price,discount,Payment_Method,Order_Status,Rating,Total
0,1001,2026-01-05,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Laptop,1,65000,0.10,Credit Card,Delivered,5.0,6500.0
1,1002,2026-01-07,C002,Priya,Female,32,Mumbai,Maharashtra,Clothing,T-Shirt,3,800,0.05,UPI,Delivered,4.0,40.0
2,1003,2026-01-10,C003,Amit,Male,24,Nagpur,Maharashtra,Electronics,Headphones,2,2500,0.00,UPI,Delivered,5.0,0.0
3,1004,2026-01-12,C004,Neha,Female,29,Bangalore,Karnataka,Furniture,Chair,2,4500,0.15,Debit Card,Delivered,4.0,675.0
4,1005,2026-01-15,C005,Rohit,Male,35,Delhi,Delhi,Electronics,Mobile Phone,1,28000,0.08,Credit Card,Delivered,5.0,2240.0

In [89]:
# creating a new column using lambda function
# with lambda function always use assign method

df = df.assign( total_02 = lambda x: x.Total*2)
df.head()

,Order_Id,Order_Date,Customer_Id,Customer_Name,Gender,Age,City,State,Product_Category,Product,Quantity,unit_price,discount,Payment_Method,Order_Status,Rating,Total,total_02
0,1001,2026-01-05,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Laptop,1,65000,0.10,Credit Card,Delivered,5.0,6500.0,13000.0
1,1002,2026-01-07,C002,Priya,Female,32,Mumbai,Maharashtra,Clothing,T-Shirt,3,800,0.05,UPI,Delivered,4.0,40.0,80.0
2,1003,2026-01-10,C003,Amit,Male,24,Nagpur,Maharashtra,Electronics,Headphones,2,2500,0.00,UPI,Delivered,5.0,0.0,0.0
3,1004,2026-01-12,C004,Neha,Female,29,Bangalore,Karnataka,Furniture,Chair,2,4500,0.15,Debit Card,Delivered,4.0,675.0,1350.0
4,1005,2026-01-15,C005,Rohit,Male,35,Delhi,Delhi,Electronics,Mobile Phone,1,28000,0.08,Credit Card,Delivered,5.0,2240.0,4480.0

In [98]:
# Find the total number of customers in each gender category/
df = df.groupby('state')
df.head()

,Order_Id,Order_Date,Customer_Id,Customer_Name,Gender,Age,City,State,Product_Category,Product,Quantity,unit_price,discount,Payment_Method,Order_Status,Rating,Total,total_02
0,1001,2026-01-05,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Laptop,1,65000,0.10,Credit Card,Delivered,5.0,6500.0,13000.0
1,1002,2026-01-07,C002,Priya,Female,32,Mumbai,Maharashtra,Clothing,T-Shirt,3,800,0.05,UPI,Delivered,4.0,40.0,80.0
2,1003,2026-01-10,C003,Amit,Male,24,Nagpur,Maharashtra,Electronics,Headphones,2,2500,0.00,UPI,Delivered,5.0,0.0,0.0
3,1004,2026-01-12,C004,Neha,Female,29,Bangalore,Karnataka,Furniture,Chair,2,4500,0.15,Debit Card,Delivered,4.0,675.0,1350.0
4,1005,2026-01-15,C005,Rohit,Male,35,Delhi,Delhi,Electronics,Mobile Phone,1,28000,0.08,Credit Card,Delivered,5.0,2240.0,4480.0
5,1006,2026-01-18,C006,Sneha,Female,27,Hyderabad,Telangana,Clothing,Jeans,2,2200,0.10,UPI,Delivered,4.0,220.0,440.0
6,1007,2026-01-20,C007,Vikas,Male,41,Pune,Maharashtra,Grocery,Rice,5,900,0.03,UPI,Delivered,4.0,27.0,54.0
7,1008,2026-01-23,C008,Anjali,Female,23,Mumbai,Maharashtra,Beauty,Face Cream,4,650,0.05,Credit Card,Delivered,5.0,32.5,65.0
8,1009,2026-01-25,C009,Karan,Male,31,Chennai,Tamil Nadu,Electronics,Smart Watch,1,7500,0.12,Debit Card,Delivered,4.0,900.0,1800.0
9,1010,2026-01-28,C010,Pooja,Female,38,Delhi,Delhi,Furniture,Sofa,1,32000,0.20,Credit Card,Cancelled,NaN,6400.0,12800.0
10,1011,2026-02-02,C011,Akash,Male,26,Pune,Maharashtra,Electronics,Keyboard,2,1800,0.00,UPI,Delivered,4.0,0.0,0.0
11,1012,2026-02-05,C012,Riya,Female,30,Bangalore,Karnataka,Clothing,Dress,2,3500,0.10,UPI,Delivered,5.0,350.0,700.0
12,1013,2026-02-08,C013,Manish,Male,45,Mumbai,Maharashtra,Grocery,Cooking Oil,3,1500,0.05,Cash,Delivered,3.0,75.0,150.0
13,1014,2026-02-10,C014,Kavita,Female,34,Hyderabad,Telangana,Beauty,Perfume,2,2800,0.15,Credit Card,Delivered,4.0,420.0,840.0
14,1015,2026-02-13,C015,Suresh,Male,52,Nagpur,Maharashtra,Furniture,Table,1,8500,0.10,Debit Card,Delivered,5.0,850.0,1700.0
15,1016,2026-02-16,C016,Meera,Female,25,Chennai,Tamil Nadu,Electronics,Tablet,1,22000,0.05,UPI,Delivered,4.0,1100.0,2200.0
16,1017,2026-02-18,C017,Arjun,Male,29,Pune,Maharashtra,Clothing,Shoes,2,4500,0.12,Credit Card,Delivered,5.0,540.0,1080.0
17,1018,2026-02-21,C018,Simran,Female,36,Delhi,Delhi,Grocery,Wheat,4,700,0.00,UPI,Delivered,4.0,0.0,0.0
18,1019,2026-02-24,C019,Deepak,Male,40,Mumbai,Maharashtra,Electronics,Monitor,1,14500,0.10,Credit Card,Returned,2.0,1450.0,2900.0
19,1020,2026-02-27,C020,Shweta,Female,28,Bangalore,Karnataka,Beauty,Shampoo,5,450,0.05,UPI,Delivered,4.0,22.5,45.0
20,1021,2026-03-01,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Mouse,2,1200,0.00,UPI,Delivered,5.0,0.0,0.0
21,1022,2026-03-04,C002,Priya,Female,32,Mumbai,Maharashtra,Clothing,Jacket,1,5500,0.15,Credit Card,Delivered,4.0,825.0,1650.0
22,1023,2026-03-07,C003,Amit,Male,24,Nagpur,Maharashtra,Grocery,Sugar,5,500,0.05,Cash,Delivered,3.0,25.0,50.0
23,1024,2026-03-10,C004,Neha,Female,29,Bangalore,Karnataka,Furniture,Bed,1,28000,0.20,Credit Card,Delivered,5.0,5600.0,11200.0
24,1025,2026-03-13,C005,Rohit,Male,35,Delhi,Delhi,Electronics,Power Bank,3,1800,0.10,UPI,Delivered,4.0,180.0,360.0
25,1026,2026-03-16,C006,Sneha,Female,27,Hyderabad,Telangana,Beauty,Lipstick,3,900,0.08,UPI,Delivered,5.0,72.0,144.0
28,1029,2026-03-25,C009,Karan,Male,31,Chennai,Tamil Nadu,Electronics,Earbuds,2,3200,0.05,UPI,Delivered,5.0,160.0,320.0
29,1030,2026-03-28,C010,Pooja,Female,38,Delhi,Delhi,Furniture,Dining Table,1,24000,0.15,Debit Card,Cancelled,NaN,3600.0,7200.0

In [99]:
for City, city_df in df:
    print(City)
    print(city_df)

Bangalore
    Order_Id  Order_Date Customer_Id Customer_Name  Gender  Age       City  \
3       1004  2026-01-12        C004          Neha  Female   29  Bangalore
11      1012  2026-02-05        C012          Riya  Female   30  Bangalore
19      1020  2026-02-27        C020        Shweta  Female   28  Bangalore
23      1024  2026-03-10        C004          Neha  Female   29  Bangalore

        State Product_Category  Product  Quantity  unit_price  discount  \
3   Karnataka        Furniture    Chair         2        4500      0.15
11  Karnataka         Clothing    Dress         2        3500      0.10
19  Karnataka           Beauty  Shampoo         5         450      0.05
23  Karnataka        Furniture      Bed         1       28000      0.20

   Payment_Method Order_Status  Rating   Total  total_02
3      Debit Card    Delivered     4.0   675.0    1350.0
11            UPI    Delivered     5.0   350.0     700.0
19            UPI    Delivered     4.0    22.5      45.0
23    Credit Card    Delivered     5.0  5600.0   11200.0
Chennai
    Order_Id  Order_Date Customer_Id Customer_Name  Gender  Age     City  \
8       1009  2026-01-25        C009         Karan    Male   31  Chennai
15      1016  2026-02-16        C016         Meera  Female   25  Chennai
28      1029  2026-03-25        C009         Karan    Male   31  Chennai

         State Product_Category      Product  Quantity  unit_price  discount  \
8   Tamil Nadu      Electronics  Smart Watch         1        7500      0.12
15  Tamil Nadu      Electronics       Tablet         1       22000      0.05
28  Tamil Nadu      Electronics      Earbuds         2        3200      0.05

   Payment_Method Order_Status  Rating   Total  total_02
8      Debit Card    Delivered     4.0   900.0    1800.0
15            UPI    Delivered     4.0  1100.0    2200.0
28            UPI    Delivered     5.0   160.0     320.0
Delhi
    Order_Id  Order_Date Customer_Id Customer_Name  Gender  Age   City  State  \
4       1005  2026-01-15        C005         Rohit    Male   35  Delhi  Delhi
9       1010  2026-01-28        C010         Pooja  Female   38  Delhi  Delhi
17      1018  2026-02-21        C018        Simran  Female   36  Delhi  Delhi
24      1025  2026-03-13        C005         Rohit    Male   35  Delhi  Delhi
29      1030  2026-03-28        C010         Pooja  Female   38  Delhi  Delhi

   Product_Category       Product  Quantity  unit_price  discount  \
4       Electronics  Mobile Phone         1       28000      0.08
9         Furniture          Sofa         1       32000      0.20
17          Grocery         Wheat         4         700      0.00
24      Electronics    Power Bank         3        1800      0.10
29        Furniture  Dining Table         1       24000      0.15

   Payment_Method Order_Status  Rating   Total  total_02
4     Credit Card    Delivered     5.0  2240.0    4480.0
9     Credit Card    Cancelled     NaN  6400.0   12800.0
17            UPI    Delivered     4.0     0.0       0.0
24            UPI    Delivered     4.0   180.0     360.0
29     Debit Card    Cancelled     NaN  3600.0    7200.0
Hyderabad
    Order_Id  Order_Date Customer_Id Customer_Name  Gender  Age       City  \
5       1006  2026-01-18        C006         Sneha  Female   27  Hyderabad
13      1014  2026-02-10        C014        Kavita  Female   34  Hyderabad
25      1026  2026-03-16        C006         Sneha  Female   27  Hyderabad

        State Product_Category   Product  Quantity  unit_price  discount  \
5   Telangana         Clothing     Jeans         2        2200      0.10
13  Telangana           Beauty   Perfume         2        2800      0.15
25  Telangana           Beauty  Lipstick         3         900      0.08

   Payment_Method Order_Status  Rating  Total  total_02
5             UPI    Delivered     4.0  220.0     440.0
13    Credit Card    Delivered     4.0  420.0     840.0
25            UPI    Delivered     5.0   72.0     144.0
Mumbai
    Order_Id  Order_Date Customer_Id Customer_Name  Gender  Age    City  \
1       1002  2026-01-07        C002         Priya  Female   32  Mumbai
7       1008  2026-01-23        C008        Anjali  Female   23  Mumbai
12      1013  2026-02-08        C013        Manish    Male   45  Mumbai
18      1019  2026-02-24        C019        Deepak    Male   40  Mumbai
21      1022  2026-03-04        C002         Priya  Female   32  Mumbai
27      1028  2026-03-22        C008        Anjali  Female   23  Mumbai

          State Product_Category      Product  Quantity  unit_price  discount  \
1   Maharashtra         Clothing      T-Shirt         3         800      0.05
7   Maharashtra           Beauty   Face Cream         4         650      0.05
12  Maharashtra          Grocery  Cooking Oil         3        1500      0.05
18  Maharashtra      Electronics      Monitor         1       14500      0.10
21  Maharashtra         Clothing       Jacket         1        5500      0.15
27  Maharashtra         Clothing        Skirt         2        1800      0.10

   Payment_Method Order_Status  Rating   Total  total_02
1             UPI    Delivered     4.0    40.0      80.0
7     Credit Card    Delivered     5.0    32.5      65.0
12           Cash    Delivered     3.0    75.0     150.0
18    Credit Card     Returned     2.0  1450.0    2900.0
21    Credit Card    Delivered     4.0   825.0    1650.0
27    Credit Card    Delivered     4.0   180.0     360.0
Nagpur
    Order_Id  Order_Date Customer_Id Customer_Name Gender  Age    City  \
2       1003  2026-01-10        C003          Amit   Male   24  Nagpur
14      1015  2026-02-13        C015        Suresh   Male   52  Nagpur
22      1023  2026-03-07        C003          Amit   Male   24  Nagpur

          State Product_Category     Product  Quantity  unit_price  discount  \
2   Maharashtra      Electronics  Headphones         2        2500      0.00
14  Maharashtra        Furniture       Table         1        8500      0.10
22  Maharashtra          Grocery       Sugar         5         500      0.05

   Payment_Method Order_Status  Rating  Total  total_02
2             UPI    Delivered     5.0    0.0       0.0
14     Debit Card    Delivered     5.0  850.0    1700.0
22           Cash    Delivered     3.0   25.0      50.0
Pune
    Order_Id  Order_Date Customer_Id Customer_Name Gender  Age  City  \
0       1001  2026-01-05        C001         Rahul   Male   28  Pune
6       1007  2026-01-20        C007         Vikas   Male   41  Pune
10      1011  2026-02-02        C011         Akash   Male   26  Pune
16      1017  2026-02-18        C017         Arjun   Male   29  Pune
20      1021  2026-03-01        C001         Rahul   Male   28  Pune
26      1027  2026-03-19        C007         Vikas   Male   41  Pune

          State Product_Category   Product  Quantity  unit_price  discount  \
0   Maharashtra      Electronics    Laptop         1       65000      0.10
6   Maharashtra          Grocery      Rice         5         900      0.03
10  Maharashtra      Electronics  Keyboard         2        1800      0.00
16  Maharashtra         Clothing     Shoes         2        4500      0.12
20  Maharashtra      Electronics     Mouse         2        1200      0.00
26  Maharashtra          Grocery      Milk        10          70      0.02

   Payment_Method Order_Status  Rating   Total  total_02
0     Credit Card    Delivered     5.0  6500.0   13000.0
6             UPI    Delivered     4.0    27.0      54.0
10            UPI    Delivered     4.0     0.0       0.0
16    Credit Card    Delivered     5.0   540.0    1080.0
20            UPI    Delivered     5.0     0.0       0.0
26           Cash    Delivered     4.0     1.4       2.8

In [100]:
df_Pune = df.get_group('Pune')
df_Pune

,Order_Id,Order_Date,Customer_Id,Customer_Name,Gender,Age,City,State,Product_Category,Product,Quantity,unit_price,discount,Payment_Method,Order_Status,Rating,Total,total_02
0,1001,2026-01-05,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Laptop,1,65000,0.10,Credit Card,Delivered,5.0,6500.0,13000.0
6,1007,2026-01-20,C007,Vikas,Male,41,Pune,Maharashtra,Grocery,Rice,5,900,0.03,UPI,Delivered,4.0,27.0,54.0
10,1011,2026-02-02,C011,Akash,Male,26,Pune,Maharashtra,Electronics,Keyboard,2,1800,0.00,UPI,Delivered,4.0,0.0,0.0
16,1017,2026-02-18,C017,Arjun,Male,29,Pune,Maharashtra,Clothing,Shoes,2,4500,0.12,Credit Card,Delivered,5.0,540.0,1080.0
20,1021,2026-03-01,C001,Rahul,Male,28,Pune,Maharashtra,Electronics,Mouse,2,1200,0.00,UPI,Delivered,5.0,0.0,0.0
26,1027,2026-03-19,C007,Vikas,Male,41,Pune,Maharashtra,Grocery,Milk,10,70,0.02,Cash,Delivered,4.0,1.4,2.8