In [1]:
import pandas as pd

data = {
    "order_id": ["ORD001", "ORD002", "ORD003", "ORD004", "ORD005",
                 "ORD006", "ORD007", "ORD008", "ORD009", "ORD010"],

    "order_date": [
        "2026-01-05", "2026-01-08", "2026-01-12", "2026-01-15",
        "2026-01-20", "2026-02-02", "2026-02-10", "2026-02-18",
        "2026-03-01", "2026-03-05"
    ],

    "customer_id": [101, 102, 103, 101, 104, 105, 102, 106, 107, 103],

    "customer_name": [
        "Aarav Sharma", "Priya Patil", "Rahul Verma", "Aarav Sharma",
        "Sneha Kulkarni", "Vikram Singh", "Priya Patil", "Neha Joshi",
        "Rohan Mehta", "Rahul Verma"
    ],

    "city": [
        "Pune", "Mumbai", "Bengaluru", "Pune", "Nashik",
        "Delhi", "Mumbai", "Jaipur", "Ahmedabad", "Bengaluru"
    ],

    "product": [
        "Laptop", "Mouse", "Keyboard", "Monitor", "Laptop",
        "Chair", "Mouse", "Laptop", "Keyboard", "Monitor"
    ],

    "category": [
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Furniture", "Accessories", "Electronics",
        "Accessories", "Electronics"
    ],

    "quantity": [1, 2, 1, 2, 1, 3, 4, 1, 2, 1],

    "unit_price": [
        70000, 1200, 4500, 15000, 70000,
        10000, 1200, 70000, 4500, 15000
    ],

    "discount": [
        0.10, 0.05, 0, 0.15, None,
        0.10, 0.05, None, 0.10, 0
    ],

    "payment_method": [
        "UPI", "Credit Card", "UPI", "Debit Card", "UPI",
        "Cash on Delivery", "upi", "Credit Card", "UPI", "Debit Card"
    ],

    "order_status": [
        "Delivered", "Delivered", "Shipped", "Delivered", "Cancelled",
        "Delivered", "Processing", "Delivered", "Returned", "Delivered"
    ]
}

df = pd.DataFrame(data)

df

,order_id,order_date,customer_id,customer_name,city,product,category,quantity,unit_price,discount,payment_method,order_status
0,ORD001,2026-01-05,101,Aarav Sharma,Pune,Laptop,Electronics,1,70000,0.10,UPI,Delivered
1,ORD002,2026-01-08,102,Priya Patil,Mumbai,Mouse,Accessories,2,1200,0.05,Credit Card,Delivered
2,ORD003,2026-01-12,103,Rahul Verma,Bengaluru,Keyboard,Accessories,1,4500,0.00,UPI,Shipped
3,ORD004,2026-01-15,101,Aarav Sharma,Pune,Monitor,Electronics,2,15000,0.15,Debit Card,Delivered
4,ORD005,2026-01-20,104,Sneha Kulkarni,Nashik,Laptop,Electronics,1,70000,NaN,UPI,Cancelled
5,ORD006,2026-02-02,105,Vikram Singh,Delhi,Chair,Furniture,3,10000,0.10,Cash on Delivery,Delivered
6,ORD007,2026-02-10,102,Priya Patil,Mumbai,Mouse,Accessories,4,1200,0.05,upi,Processing
7,ORD008,2026-02-18,106,Neha Joshi,Jaipur,Laptop,Electronics,1,70000,NaN,Credit Card,Delivered
8,ORD009,2026-03-01,107,Rohan Mehta,Ahmedabad,Keyboard,Accessories,2,4500,0.10,UPI,Returned
9,ORD010,2026-03-05,103,Rahul Verma,Bengaluru,Monitor,Electronics,1,15000,0.00,Debit Card,Delivered

Q1 — Read & inspect
After creating df, write Pandas code to answer:
1. Display the first 5 records.
2. Display the last 3 records.
3. Find the number of rows and columns.
4. Display all column names.
5. Display the data types of all columns.
6. Display basic statistical information about the numerical columns.

In [2]:
df.head()

,order_id,order_date,customer_id,customer_name,city,product,category,quantity,unit_price,discount,payment_method,order_status
0,ORD001,2026-01-05,101,Aarav Sharma,Pune,Laptop,Electronics,1,70000,0.10,UPI,Delivered
1,ORD002,2026-01-08,102,Priya Patil,Mumbai,Mouse,Accessories,2,1200,0.05,Credit Card,Delivered
2,ORD003,2026-01-12,103,Rahul Verma,Bengaluru,Keyboard,Accessories,1,4500,0.00,UPI,Shipped
3,ORD004,2026-01-15,101,Aarav Sharma,Pune,Monitor,Electronics,2,15000,0.15,Debit Card,Delivered
4,ORD005,2026-01-20,104,Sneha Kulkarni,Nashik,Laptop,Electronics,1,70000,NaN,UPI,Cancelled

In [3]:
df.tail(3)

,order_id,order_date,customer_id,customer_name,city,product,category,quantity,unit_price,discount,payment_method,order_status
7,ORD008,2026-02-18,106,Neha Joshi,Jaipur,Laptop,Electronics,1,70000,NaN,Credit Card,Delivered
8,ORD009,2026-03-01,107,Rohan Mehta,Ahmedabad,Keyboard,Accessories,2,4500,0.1,UPI,Returned
9,ORD010,2026-03-05,103,Rahul Verma,Bengaluru,Monitor,Electronics,1,15000,0.0,Debit Card,Delivered

In [5]:
df.shape

(10, 12)

In [7]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'customer_name', 'city',
       'product', 'category', 'quantity', 'unit_price', 'discount',
       'payment_method', 'order_status'],
      dtype='object')

In [10]:
df.dtypes

order_id           object
order_date         object
customer_id         int64
customer_name      object
city               object
product            object
category           object
quantity            int64
unit_price          int64
discount          float64
payment_method     object
order_status       object
dtype: object

In [11]:
df.describe()

       customer_id   quantity    unit_price  discount
count    10.000000  10.000000     10.000000  8.000000
mean    103.400000   1.800000  26140.000000  0.068750
std       2.065591   1.032796  30660.115242  0.053033
min     101.000000   1.000000   1200.000000  0.000000
25%     102.000000   1.000000   4500.000000  0.037500
50%     103.000000   1.500000  12500.000000  0.075000
75%     104.750000   2.000000  56250.000000  0.100000
max     107.000000   4.000000  70000.000000  0.150000

Display the first row of the DataFrame using loc[]

In [13]:
df.loc[0]

order_id                ORD001
order_date          2026-01-05
customer_id                101
customer_name     Aarav Sharma
city                      Pune
product                 Laptop
category           Electronics
quantity                     1
unit_price               70000
discount                   0.1
payment_method             UPI
order_status         Delivered
Name: 0, dtype: object

Q8
Using loc[], display rows with index 2 through 5.

In [14]:
df.loc[2:5]

,order_id,order_date,customer_id,customer_name,city,product,category,quantity,unit_price,discount,payment_method,order_status
2,ORD003,2026-01-12,103,Rahul Verma,Bengaluru,Keyboard,Accessories,1,4500,0.00,UPI,Shipped
3,ORD004,2026-01-15,101,Aarav Sharma,Pune,Monitor,Electronics,2,15000,0.15,Debit Card,Delivered
4,ORD005,2026-01-20,104,Sneha Kulkarni,Nashik,Laptop,Electronics,1,70000,NaN,UPI,Cancelled
5,ORD006,2026-02-02,105,Vikram Singh,Delhi,Chair,Furniture,3,10000,0.10,Cash on Delivery,Delivered

`Q9 — loc[] with columns
-- Now select rows 2 through 5, but display only these columns:
-- customer_name
-- city
-- product`