# PANDAS

### 1. reading dat from datasets and creating df
### 2. viewing data using loc[] and iloc[]
### 3. basic operations on df
### 4. handling missing data
### 5. sorting the data

data frame is the object which stores data in rows and columns 

series -> is an object that contains only 1 col.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/Users/onkar/Downloads/datasets1/empdata.csv")
df

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [3]:
df[df.sal > 20000]

   empid       ename      sal         doj
1   1002  Anil Kumar  23000.5  2002-03-03

In [4]:
df[df.sal > 20000][['ename','sal']]

        ename      sal
1  Anil Kumar  23000.5

& represent boolean

In [5]:
df[(df.sal >15000) & (df.sal<20000)]

   empid         ename       sal         doj
2   1003  Gaurav Gupta  18000.33  2002-03-03
3   1004  Hema Chandra  16500.50  2002-03-03

In [6]:
df[(df.sal >15000) & (df.sal<20000)][['empid','sal']]

   empid       sal
2   1003  18000.33
3   1004  16500.50

display emp data where sal is max

In [7]:
df[df['sal'] == df['sal'].max()]

   empid       ename      sal         doj
1   1002  Anil Kumar  23000.5  2002-03-03

display the records where salary is above avg salary

In [8]:
df[df['sal'] > df['sal'].mean()]

   empid         ename       sal         doj
1   1002    Anil Kumar  23000.50  2002-03-03
2   1003  Gaurav Gupta  18000.33  2002-03-03
3   1004  Hema Chandra  16500.50  2002-03-03

OR we can write in both formant

In [9]:
df[df.sal > df.sal.mean()]

   empid         ename       sal         doj
1   1002    Anil Kumar  23000.50  2002-03-03
2   1003  Gaurav Gupta  18000.33  2002-03-03
3   1004  Hema Chandra  16500.50  2002-03-03

In [10]:
df[df.sal > df.sal.mean()]['ename'] # just ename i want

1      Anil Kumar
2    Gaurav Gupta
3    Hema Chandra
Name: ename, dtype: object

In [11]:
df.index # to display the index from the output

RangeIndex(start=0, stop=6, step=1)

In [12]:
df.set_index('empid', inplace = True) # thid will change aoutomatic index to empid
df

                ename       sal         doj
empid
1001       Ganesh Rao  10000.00  2000-10-10
1002       Anil Kumar  23000.50  2002-03-03
1003     Gaurav Gupta  18000.33  2002-03-03
1004     Hema Chandra  16500.50  2002-03-03
1005   Laxmi Prasanna  12000.75  2000-08-10
1006        Anant Nag   9999.99  1999-09-09

In [13]:
df.loc[1002]

ename    Anil Kumar
sal         23000.5
doj      2002-03-03
Name: 1002, dtype: object

In [14]:
# to reset the index 
df.reset_index(inplace =True)
df

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

# Handling Missing Values

In [15]:
df1 = pd.read_csv("/Users/onkar/Downloads/datasets1/empdata1.csv")
df1

   empid           ename       sal       doj
0   1001      Ganesh Rao  10000.00  10-10-00
1   1002      Anil Kumar  23000.50  03-03-02
2   1003             NaN  18000.33  03-03-02
3   1004    Hema Chandra       NaN       NaN
4   1005  Laxmi Prasanna  12000.75  10-08-00
5   1006       Anant Nag   9999.99  09-09-99

In [16]:
# filling Nan with 0

df1.fillna(0)

   empid           ename       sal       doj
0   1001      Ganesh Rao  10000.00  10-10-00
1   1002      Anil Kumar  23000.50  03-03-02
2   1003               0  18000.33  03-03-02
3   1004    Hema Chandra      0.00         0
4   1005  Laxmi Prasanna  12000.75  10-08-00
5   1006       Anant Nag   9999.99  09-09-99

In [17]:
# different columns empty values with different values 
df2 = df1.fillna({'ename':'Missing','sal':0.00,'doj':'1-1-2000'}) # we are storing in different dataframe
df2

   empid           ename       sal       doj
0   1001      Ganesh Rao  10000.00  10-10-00
1   1002      Anil Kumar  23000.50  03-03-02
2   1003         Missing  18000.33  03-03-02
3   1004    Hema Chandra      0.00  1-1-2000
4   1005  Laxmi Prasanna  12000.75  10-08-00
5   1006       Anant Nag   9999.99  09-09-99

In [18]:
# i want to replace NAN with avg of sal

df3 = df1.fillna({'ename':'Missing','sal': df.sal.mean(),'doj':'1-1-2000'}) # we are storing in different dataframe
df3

   empid           ename           sal       doj
0   1001      Ganesh Rao  10000.000000  10-10-00
1   1002      Anil Kumar  23000.500000  03-03-02
2   1003         Missing  18000.330000  03-03-02
3   1004    Hema Chandra  14917.011667  1-1-2000
4   1005  Laxmi Prasanna  12000.750000  10-08-00
5   1006       Anant Nag   9999.990000  09-09-99

In [19]:
# it will remove records from the data where NAN(null Values) is prenent

df1.dropna()

   empid           ename       sal       doj
0   1001      Ganesh Rao  10000.00  10-10-00
1   1002      Anil Kumar  23000.50  03-03-02
4   1005  Laxmi Prasanna  12000.75  10-08-00
5   1006       Anant Nag   9999.99  09-09-99

In [20]:
# how to read date column as date as by default it is read as string

df2 = pd.read_csv("/Users/onkar/Downloads/datasets1/empdata.csv",parse_dates = ['doj'])
df2

   empid           ename       sal        doj
0   1001      Ganesh Rao  10000.00 2000-10-10
1   1002      Anil Kumar  23000.50 2002-03-03
2   1003    Gaurav Gupta  18000.33 2002-03-03
3   1004    Hema Chandra  16500.50 2002-03-03
4   1005  Laxmi Prasanna  12000.75 2000-08-10
5   1006       Anant Nag   9999.99 1999-09-09

In [21]:
# sort values by default is ASC

df2.sort_values('ename')

   empid           ename       sal        doj
5   1006       Anant Nag   9999.99 1999-09-09
1   1002      Anil Kumar  23000.50 2002-03-03
0   1001      Ganesh Rao  10000.00 2000-10-10
2   1003    Gaurav Gupta  18000.33 2002-03-03
3   1004    Hema Chandra  16500.50 2002-03-03
4   1005  Laxmi Prasanna  12000.75 2000-08-10

In [22]:
# sort values in desc

df2.sort_values('ename', ascending = False)

   empid           ename       sal        doj
4   1005  Laxmi Prasanna  12000.75 2000-08-10
3   1004    Hema Chandra  16500.50 2002-03-03
2   1003    Gaurav Gupta  18000.33 2002-03-03
0   1001      Ganesh Rao  10000.00 2000-10-10
1   1002      Anil Kumar  23000.50 2002-03-03
5   1006       Anant Nag   9999.99 1999-09-09

In [23]:
# sort on doj

df2.sort_values('doj', ascending = False)

   empid           ename       sal        doj
1   1002      Anil Kumar  23000.50 2002-03-03
2   1003    Gaurav Gupta  18000.33 2002-03-03
3   1004    Hema Chandra  16500.50 2002-03-03
0   1001      Ganesh Rao  10000.00 2000-10-10
4   1005  Laxmi Prasanna  12000.75 2000-08-10
5   1006       Anant Nag   9999.99 1999-09-09

In [24]:
df2.sort_values(by =['doj','sal'], ascending = [False, True])

   empid           ename       sal        doj
3   1004    Hema Chandra  16500.50 2002-03-03
2   1003    Gaurav Gupta  18000.33 2002-03-03
1   1002      Anil Kumar  23000.50 2002-03-03
0   1001      Ganesh Rao  10000.00 2000-10-10
4   1005  Laxmi Prasanna  12000.75 2000-08-10
5   1006       Anant Nag   9999.99 1999-09-09

# series

In [25]:
df3 = pd.read_csv("/Users/onkar/Downloads/datasets1/nba.csv")
df3

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,06-Feb,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,06-Jun,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,06-May,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,06-May,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,06-Oct,231,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,06-Oct,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,06-Mar,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,06-Jan,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,07-Mar,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0

In [26]:
s1 =pd.Series(df3.Name)
s1

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
452       Trey Lyles
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
Name: Name, Length: 457, dtype: object

In [27]:
s2 = pd.Series(df3.Age)
s2

0      25
1      25
2      27
3      22
4      29
       ..
452    20
453    26
454    24
455    26
456    26
Name: Age, Length: 457, dtype: int64

In [28]:
df4 = pd.concat([s1,s2],axis=1)
df4

              Name  Age
0    Avery Bradley   25
1      Jae Crowder   25
2     John Holland   27
3      R.J. Hunter   22
4    Jonas Jerebko   29
..             ...  ...
452     Trey Lyles   20
453   Shelvin Mack   26
454      Raul Neto   24
455   Tibor Pleiss   26
456    Jeff Withey   26

[457 rows x 2 columns]

In [29]:
df4.columns = ['sportsperson','personAge']
df4

      sportsperson  personAge
0    Avery Bradley         25
1      Jae Crowder         25
2     John Holland         27
3      R.J. Hunter         22
4    Jonas Jerebko         29
..             ...        ...
452     Trey Lyles         20
453   Shelvin Mack         26
454      Raul Neto         24
455   Tibor Pleiss         26
456    Jeff Withey         26

[457 rows x 2 columns]

In [30]:
# creating a dataframe with names change 
# we have to create ddictionry 

mydict ={'empname': s1,'empage':s2}
df4 = pd.DataFrame(mydict)
df4

           empname  empage
0    Avery Bradley      25
1      Jae Crowder      25
2     John Holland      27
3      R.J. Hunter      22
4    Jonas Jerebko      29
..             ...     ...
452     Trey Lyles      20
453   Shelvin Mack      26
454      Raul Neto      24
455   Tibor Pleiss      26
456    Jeff Withey      26

[457 rows x 2 columns]

In [31]:
# numpy array to pandas series object

import numpy as np

arr =np.array([10,22,33,40])
arr

array([10, 22, 33, 40])

In [32]:
ser = pd.Series(arr) 
ser

0    10
1    22
2    33
3    40
dtype: int64

In [33]:
arr1 = ser.values
arr1

array([10, 22, 33, 40])

In [34]:
# sereies object to dictonery 

dt = {'name':['raj','viany','onkar','ayush'],
      'age':[33,44,56,23],
      'deg':['se','de','de1','qa']}

In [35]:
# sereies object to dictonery 

s = pd.Series(dt)
s

name    [raj, viany, onkar, ayush]
age               [33, 44, 56, 23]
deg              [se, de, de1, qa]
dtype: object

In [36]:
# to access first person name 
s['name'][0]

'raj'

In [37]:
df = pd.read_csv("/Users/onkar/Downloads/datasets1/empdata.csv")
df

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [39]:
df.sal = df.sal+50000
df

   empid           ename        sal         doj
0   1001      Ganesh Rao  110000.00  2000-10-10
1   1002      Anil Kumar  123000.50  2002-03-03
2   1003    Gaurav Gupta  118000.33  2002-03-03
3   1004    Hema Chandra  116500.50  2002-03-03
4   1005  Laxmi Prasanna  112000.75  2000-08-10
5   1006       Anant Nag  109999.99  1999-09-09

In [41]:
df.loc[6] = [1007,'subbarao',55000.55,'2000-10-21']
print(df)

   empid           ename        sal         doj
0   1001      Ganesh Rao  110000.00  2000-10-10
1   1002      Anil Kumar  123000.50  2002-03-03
2   1003    Gaurav Gupta  118000.33  2002-03-03
3   1004    Hema Chandra  116500.50  2002-03-03
4   1005  Laxmi Prasanna  112000.75  2000-08-10
5   1006       Anant Nag  109999.99  1999-09-09
6   1007        subbarao   55000.55  2000-10-21


#to save output in csv

In [43]:
#to save output in csv

df.to_csv("/Users/onkar/Downloads/datasets1/new_empdata.csv")

In [45]:
#to save output in excel

df.to_excel("/Users/onkar/Downloads/datasets1/empNew_empdata.xlsx")